# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/malik/Documents/ECE_520_PROJECTS/LAB11_MALIK/BD/webserver_design/ip/webserver_design_processing_system7_0_0/webserver_design_processing_system7_0_0.xci
# IP: The module: 'webserver_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/malik/Documents/ECE_520_PROJECTS/LAB11_MALIK/BD/webserver_design/ip/webserver_design_processing_system7_0_0/webserver_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'webserver_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/malik/Documents/ECE_520_PROJECTS/LAB11_MALIK/BD/webserver_design/ip/webserver_design_processing_system7_0_0/webserver_design_processing_system7_0_0.xci
# IP: The module: 'webserver_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/malik/Documents/ECE_520_PROJECTS/LAB11_MALIK/BD/webserver_design/ip/webserver_design_processing_system7_0_0/webserver_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'webserver_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
