# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/webserver.xdc

# Block Designs: C:/Users/malik/Documents/ECE_520_PROJECTS/LAB11_MALIK/BD/webserver_design/webserver_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==webserver_design || ORIG_REF_NAME==webserver_design} -quiet] -quiet

# IP: c:/Users/malik/Documents/ECE_520_PROJECTS/LAB11_MALIK/BD/webserver_design/ip/webserver_design_processing_system7_0_0/webserver_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==webserver_design_processing_system7_0_0 || ORIG_REF_NAME==webserver_design_processing_system7_0_0} -quiet] -quiet

# IP: c:/Users/malik/Documents/ECE_520_PROJECTS/LAB11_MALIK/BD/webserver_design/ip/webserver_design_axi_gpio_0_1/webserver_design_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==webserver_design_axi_gpio_0_1 || ORIG_REF_NAME==webserver_design_axi_gpio_0_1} -quiet] -quiet

# IP: c:/Users/malik/Documents/ECE_520_PROJECTS/LAB11_MALIK/BD/webserver_design/ip/webserver_design_ps7_0_axi_periph_0/webserver_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==webserver_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==webserver_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: c:/Users/malik/Documents/ECE_520_PROJECTS/LAB11_MALIK/BD/webserver_design/ip/webserver_design_rst_ps7_0_50M_0/webserver_design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==webserver_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==webserver_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: c:/Users/malik/Documents/ECE_520_PROJECTS/LAB11_MALIK/BD/webserver_design/ip/webserver_design_auto_pc_0/webserver_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==webserver_design_auto_pc_0 || ORIG_REF_NAME==webserver_design_auto_pc_0} -quiet] -quiet

# XDC: C:/Users/malik/Documents/ECE_520_PROJECTS/LAB11_MALIK/BD/webserver_design/webserver_design_ooc.xdc
